# -*- coding: utf-8 -*-
"""Personal: AI (CV: Segmentation Instance, Sheep)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UpiCVN4Y78u3PW1eFP0ky8ynaYH9WtHp
"""

# Installations
!pip install tensorflow==2.7.0
!pip install pixellib
!pip install -U pillow

# Imports
import pixellib
import matplotlib.pyplot as plt
from pixellib.instance import instance_segmentation
from pixellib.semantic import semantic_segmentation

# Variables
model = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//mask_rcnn_coco.h5"
input_image = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//CountingSheep.jpeg"
output_image = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//CountingSheep_Segmented.jpeg"

# Instance Segmentation
segment_video = instance_segmentation()
segment_video.load_model(model)
segment_video.process_video(input_image, frames_per_second= 20, output_video_name = output_image)